const char* const coinxp_latestprice_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-08-21T10:15:25",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "Price",
      "base": "",
      "fields": [{
          "name": "amount",
          "type": "uint64"
        },{
          "name": "price",
          "type": "uint64"
        },{
          "name": "timestamp",
          "type": "uint64"
        }
      ]
    },{
      "name": "updateprice",
      "base": "",
      "fields": [{
          "name": "scope",
          "type": "uint64"
        },{
          "name": "amount",
          "type": "uint64"
        },{
          "name": "price",
          "type": "uint64"
        }
      ]
    }
  ],
  "actions": [{
      "name": "updateprice",
      "type": "updateprice",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "price",
      "index_type": "i64",
      "key_names": [
        "amount"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "Price"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": []
})=====";
