const char* const coinxp_exchange_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-08-21T10:15:05",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "account_asset",
      "base": "",
      "fields": [{
          "name": "balance",
          "type": "asset"
        },{
          "name": "locked",
          "type": "asset"
        },{
          "name": "frozen",
          "type": "bool"
        }
      ]
    },{
      "name": "currency",
      "base": "",
      "fields": [{
          "name": "supply",
          "type": "asset"
        }
      ]
    },{
      "name": "lock",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        }
      ]
    },{
      "name": "unlock",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        }
      ]
    },{
      "name": "subbalance",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        }
      ]
    },{
      "name": "sublocked",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        }
      ]
    },{
      "name": "addbalance",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        }
      ]
    }
  ],
  "actions": [{
      "name": "lock",
      "type": "lock",
      "ricardian_contract": ""
    },{
      "name": "unlock",
      "type": "unlock",
      "ricardian_contract": ""
    },{
      "name": "subbalance",
      "type": "subbalance",
      "ricardian_contract": ""
    },{
      "name": "sublocked",
      "type": "sublocked",
      "ricardian_contract": ""
    },{
      "name": "addbalance",
      "type": "addbalance",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "accountasset",
      "index_type": "i64",
      "key_names": [
        "balance"
      ],
      "key_types": [
        "asset"
      ],
      "type": "account_asset"
    },{
      "name": "stat",
      "index_type": "i64",
      "key_names": [
        "supply"
      ],
      "key_types": [
        "asset"
      ],
      "type": "currency"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": []
})=====";
