const char* const coinxp_orderdb_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-08-21T10:15:17",
  "version": "eosio::abi/1.0",
  "types": [{
      "new_type_name": "symbol_name",
      "type": "uint64"
    }
  ],
  "structs": [{
      "name": "OrderDb",
      "base": "",
      "fields": [{
          "name": "request_id",
          "type": "uint64"
        },{
          "name": "orderbook_key",
          "type": "uint64"
        },{
          "name": "scope",
          "type": "uint64"
        },{
          "name": "currency_symbol",
          "type": "symbol_name"
        },{
          "name": "commodity_symbol",
          "type": "symbol_name"
        },{
          "name": "is_buy",
          "type": "bool"
        },{
          "name": "traded_currency",
          "type": "uint64"
        },{
          "name": "traded_commodity",
          "type": "uint64"
        },{
          "name": "price",
          "type": "uint64"
        },{
          "name": "pending_commodity",
          "type": "uint64"
        },{
          "name": "status",
          "type": "uint16"
        },{
          "name": "timestamp",
          "type": "uint64"
        }
      ]
    },{
      "name": "record",
      "base": "",
      "fields": [{
          "name": "user",
          "type": "name"
        },{
          "name": "request_id",
          "type": "uint64"
        },{
          "name": "orderbook_key",
          "type": "uint64"
        },{
          "name": "scope",
          "type": "uint64"
        },{
          "name": "currency_symbol",
          "type": "symbol_name"
        },{
          "name": "commodity_symbol",
          "type": "symbol_name"
        },{
          "name": "is_buy",
          "type": "bool"
        },{
          "name": "traded_currency",
          "type": "uint64"
        },{
          "name": "traded_commodity",
          "type": "uint64"
        },{
          "name": "price",
          "type": "uint64"
        },{
          "name": "pending_commodity",
          "type": "uint64"
        },{
          "name": "status",
          "type": "uint16"
        }
      ]
    },{
      "name": "update",
      "base": "",
      "fields": [{
          "name": "user",
          "type": "name"
        },{
          "name": "request_id",
          "type": "uint64"
        },{
          "name": "delta_amount",
          "type": "uint64"
        },{
          "name": "fully_taken",
          "type": "bool"
        }
      ]
    },{
      "name": "markcancel",
      "base": "",
      "fields": [{
          "name": "user",
          "type": "name"
        },{
          "name": "request_id",
          "type": "uint64"
        }
      ]
    }
  ],
  "actions": [{
      "name": "record",
      "type": "record",
      "ricardian_contract": ""
    },{
      "name": "update",
      "type": "update",
      "ricardian_contract": ""
    },{
      "name": "markcancel",
      "type": "markcancel",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "orderdb",
      "index_type": "i64",
      "key_names": [
        "request_id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "OrderDb"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": []
})=====";
