const char* const coinxp_match_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-10-10T11:59:37",
  "version": "eosio::abi/1.0",
  "types": [{
      "new_type_name": "symbol_name",
      "type": "uint64"
    }
  ],
  "structs": [{
      "name": "CoinPair",
      "base": "",
      "fields": [{
          "name": "currency",
          "type": "symbol_code"
        },{
          "name": "commodity",
          "type": "symbol_code"
        },{
          "name": "timestamp",
          "type": "uint64"
        }
      ]
    },{
      "name": "BuyOrder",
      "base": "",
      "fields": [{
          "name": "auto_key",
          "type": "uint64"
        },{
          "name": "request_id",
          "type": "uint64"
        },{
          "name": "price",
          "type": "float64"
        },{
          "name": "amount",
          "type": "int64"
        },{
          "name": "timestamp",
          "type": "uint64"
        },{
          "name": "user",
          "type": "name"
        },{
          "name": "exchange",
          "type": "name"
        },{
          "name": "bitmap",
          "type": "uint64"
        },{
          "name": "reserved0",
          "type": "uint64"
        },{
          "name": "reserved1",
          "type": "uint64"
        },{
          "name": "reserved2",
          "type": "uint64"
        },{
          "name": "reserved3",
          "type": "uint64"
        }
      ]
    },{
      "name": "SellOrder",
      "base": "",
      "fields": [{
          "name": "auto_key",
          "type": "uint64"
        },{
          "name": "request_id",
          "type": "uint64"
        },{
          "name": "price",
          "type": "float64"
        },{
          "name": "amount",
          "type": "int64"
        },{
          "name": "timestamp",
          "type": "uint64"
        },{
          "name": "user",
          "type": "name"
        },{
          "name": "exchange",
          "type": "name"
        },{
          "name": "bitmap",
          "type": "uint64"
        },{
          "name": "reserved0",
          "type": "uint64"
        },{
          "name": "reserved1",
          "type": "uint64"
        },{
          "name": "reserved2",
          "type": "uint64"
        },{
          "name": "reserved3",
          "type": "uint64"
        }
      ]
    },{
      "name": "addpair",
      "base": "",
      "fields": [{
          "name": "currency",
          "type": "asset"
        },{
          "name": "commodity",
          "type": "asset"
        }
      ]
    },{
      "name": "showpairs",
      "base": "",
      "fields": []
    },{
      "name": "ask",
      "base": "",
      "fields": [{
          "name": "user",
          "type": "name"
        },{
          "name": "exchange",
          "type": "name"
        },{
          "name": "currency",
          "type": "asset"
        },{
          "name": "commodity",
          "type": "asset"
        },{
          "name": "is_buy",
          "type": "bool"
        },{
          "name": "request_id",
          "type": "uint64"
        }
      ]
    },{
      "name": "cancel",
      "base": "",
      "fields": [{
          "name": "user",
          "type": "name"
        },{
          "name": "currency",
          "type": "asset"
        },{
          "name": "commodity",
          "type": "asset"
        },{
          "name": "is_buy",
          "type": "bool"
        },{
          "name": "key",
          "type": "uint64"
        }
      ]
    },{
      "name": "cancelapi",
      "base": "",
      "fields": [{
          "name": "user",
          "type": "name"
        },{
          "name": "scope",
          "type": "uint64"
        },{
          "name": "key",
          "type": "uint64"
        },{
          "name": "is_buy",
          "type": "bool"
        },{
          "name": "symbol",
          "type": "symbol_name"
        }
      ]
    }
  ],
  "actions": [{
      "name": "addpair",
      "type": "addpair",
      "ricardian_contract": ""
    },{
      "name": "showpairs",
      "type": "showpairs",
      "ricardian_contract": ""
    },{
      "name": "ask",
      "type": "ask",
      "ricardian_contract": ""
    },{
      "name": "cancel",
      "type": "cancel",
      "ricardian_contract": ""
    },{
      "name": "cancelapi",
      "type": "cancelapi",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "coin",
      "index_type": "i64",
      "key_names": [
        "currency"
      ],
      "key_types": [
        "symbol_code"
      ],
      "type": "CoinPair"
    },{
      "name": "buybook",
      "index_type": "i64",
      "key_names": [
        "auto_key"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "BuyOrder"
    },{
      "name": "sellbook",
      "index_type": "i64",
      "key_names": [
        "auto_key"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "SellOrder"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": []
})=====";
